#!/usr/bin/perl
use strict;
sub grep_file {
    my ($file, $pat) = @_;
    my $l = `grep '$pat' -n $file`;
    while($l=~/^\s*(\d+):\s+(.*)/mg){
        print "  line $1:\t$2\n";
    }
}

my $mydef_page = `which mydef_page`;
chomp $mydef_page;
print "mydef_page: $mydef_page\n";
grep_file($mydef_page, 'MyDef::createpage');
print "\n  MyDef::createpage\n";
print "    my \$plines=MyDef::compileutil::compile();\n";
print "    MyDef::compileutil::output(\$plines);\n";
print "\n  MyDef::compileutil::compile\n";
print "    parse_code(\$maincode);\n";
print "    \$f_parse->(\"NOOP POST_MAIN\")\n";
print "    ...\n";
print "    \$f_dumpout->(\@buffer, fetch_output(0), \$page->{pageext})\n";
if($mydef_page=~/(.*)\/bin\/mydef_page/){
    my $lib_dir="$1/lib/perl5/MyDef";
    my $f = "$lib_dir/dumpout.pm";
    if(-f $f){
        print "\n  MyDef::dumpout::dumpout\n";
        grep_file($f, '\^\(INCLUDE_BLOCK\|DUMP_STUB\)');
    }
    my $f = "$lib_dir/output_c.pm";
    if(-f $f){
        print "\n  MyDef::output_c::parsecode\n";
        grep_file($f, '\^NOOP POST_MAIN');
    }
}
