#!/usr/bin/perl
use strict;
our $b_force;

sub install_all {
    my ($install_dir, $ext) = @_;
    my @files=glob("*");
    my @srcs;
    my @dirs;
    foreach my $f (@files){
        if(-d $f){
            push @dirs, $f;
        }
        elsif($ext eq "-"){
            push @srcs, $f;
        }
        elsif($f=~/\.$ext$/){
            push @srcs, $f;
        }
    }
    foreach my $d (@dirs){
        if(-f "$d/skip"){
            next;
        }
        my $pat = "$d/*.$ext";
        if($ext eq "-"){
            $pat = "$d/*";
        }
        my @files=glob($pat);
        if(@files){
            if(!-d "$install_dir/$d"){
                mkdir "$install_dir/$d" or die "Can't mkdir $install_dir/$d";
            }
            foreach my $f (@files){
                push @srcs, $f;
            }
        }
    }
    my $i = 0;
    foreach my $src (@srcs){
        my $dst="$install_dir/$src";
        if(!-e $dst or $b_force or -M $src < -M $dst){
            if($i==0){
                print "install_all: $install_dir [$ext]\n";
            }
            $i++;
            print "  :| $src -> $dst\n";
            if($ext eq "-"){
                system "install -m555 $src $dst";
            }
            else{
                system "install -m644 $src $dst";
            }
        }
    }
}

if($ARGV[0] eq "-f"){
    $b_force = 1;
    shift @ARGV;
}
my ($src, $dst, $ext)=($ARGV[0], $ARGV[1], $ARGV[2]);
if(!$ext){
    $ext = "def";
}
my $home = $ENV{HOME};
my $install_dir;
if($dst=~/^(\/.*)/){
    $install_dir=$1;
    $dst = ".";
}
elsif($ext eq "def"){
    $install_dir=$ENV{MYDEFLIB};
    $install_dir=~s/:.*//;
    if(!$install_dir){
        print "Missing environment variable MYDEFLIB\n";
        print "    try put 'MYDEFLIB=\$HOME/lib/MyDef' in your .bashrc (and source it)\n";
        exit;
    }
}
elsif($ext eq "pm"){
    $install_dir=$ENV{PERL5LIB};
    $install_dir=~s/:.*//;
    if(!$install_dir){
        print "Missing environment variable PERL5LIB\n";
        print "    try put 'PERL5LIB=\$HOME/lib/perl5' in your .bashrc (and source it)\n";
        exit;
    }
}
elsif($ext eq "-"){
    $install_dir=$ENV{PATH};
    $install_dir=~s/:.*//;
    if($install_dir ne "$home/bin"){
        print "This will install script into your leading path: [$install_dir]\n";
        print "  press 'y' to continute (abort otherwise)\n";
        my $t =<STDIN>;
        if($t!~/^\s*y\s*$/){
            undef $install_dir;
        }
    }
    if(!$install_dir){
        print "Missing environment variable PATH\n";
        print "    try put 'PATH=\$HOME/bin' in your .bashrc (and source it)\n";
        exit;
    }
}
if(!-d $install_dir){
    mkdir $install_dir or die "Can't mkdir $install_dir\n";
}
if(!$src or !$dst){
    die "Usage: $0 src dst\n";
}
if($src ne "."){
    chdir $src or die "Can't chdir $src\n";
}
if($dst ne "."){
    $install_dir.="/$dst";
    if(!-d $install_dir){
        mkdir $install_dir or die "Can't mkdir $install_dir\n";
    }
}
install_all($install_dir, $ext);
